SET NAMES utf8mb4;

DROP SCHEMA IF EXISTS catCafe;
CREATE SCHEMA catCafe;
USE catCafe;

CREATE TABLE Cats (
  catID				INT				NOT NULL AUTO_INCREMENT,
  name 				VARCHAR(50)		NOT NULL UNIQUE,	-- won't allow repeated names
  age 				INT 			NOT NULL,
  personality		VARCHAR(255)	NOT NULL,
  PRIMARY KEY (catID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Menu (
  menuID			INT 		NOT NULL AUTO_INCREMENT,
  item			VARCHAR(50)	NOT NULL,
  price			FLOAT		NOT NULL,
  PRIMARY KEY (menuID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;